Link.create("title"=>"codegangsta", "url"=>"https://codegangsta.io/", "active"=>true)
Link.create("title"=>"MSH", "url"=>"http://hertzber.gs/", "active"=>true)
Link.create("title"=>"hoursintheday", "url"=>"https://medium.com/@itsmeduncan/you-only-have-so-many-hours-in-the-day-a8c004a21d72#.kk2gwrcu0", "active"=>false)
Link.create("title"=>"Retro Pie HOWTO", "url"=>"https://github.com/RetroPie/RetroPie-Setup/wiki", "active"=>true)
Link.create("title"=>"Build Measure Learn (New Relic)", "url"=>"http://newrelic.com/webinars/leanstartup", "active"=>true)
Link.create("title"=>"Interview This", "url"=>"https://github.com/ChiperSoft/InterviewThis", "active"=>true)
Link.create("title"=>"Star Wars Creator", "url"=>"http://brorlandi.github.io/StarWarsIntroCreator/", "active"=>true)
Link.create("title"=>"Ma new Car?", "url"=>"http://www.ballinderrycarsales.co.uk/used-cars/volkswagen-passat-1-6-tdi-bluemotion-tech-se-4dr-moira-201504162664691", "active"=>false)
Link.create("title"=>"New Spree", "url"=>"https://github.com/solidusio/solidus", "active"=>true)
Link.create("title"=>"Trix", "url"=>"https://github.com/basecamp/trix", "active"=>true)
Link.create("title"=>"Plagueis", "url"=>"https://www.youtube.com/watch?v=7A3g3Pov9U0", "active"=>true)
Link.create("title"=>"Black Dog Phone", "url"=>"http://theblack-dog.com/contactus.html", "active"=>true)
Link.create("title"=>"Go Lang", "url"=>"https://golang.org/", "active"=>true)
Link.create("title"=>"Building Web Apps", "url"=>"https://www.gitbook.com/book/codegangsta/building-web-apps-with-go/details", "active"=>true)
Link.create("title"=>"Virtual Office", "url"=>"https://www.hoxtonmix.com/virtual-office-collect/", "active"=>true)
Link.create("title"=>"Sandi Metz Rules", "url"=>"https://robots.thoughtbot.com/sandi-metz-rules-for-developers", "active"=>true)
Link.create("title"=>"dhh @ full stack radio", "url"=>"http://www.fullstackradio.com/32", "active"=>true)
Link.create("title"=>"Website Obesity", "url"=>"http://idlewords.com/talks/website_obesity.htm", "active"=>true)
Link.create("title"=>"Ryan Tomayko", "url"=>"http://2ndscale.com/", "active"=>true)
Link.create("title"=>"Portal", "url"=>"https://shopkeep.atlassian.net/servicedesk/customer/portals", "active"=>true)
Link.create("title"=>"Inventory Tracking", "url"=>"https://github.com/shopkeep/proposals/blob/inventory-tracking-service/design/services/2015-12-01-inventory-tracking.md", "active"=>true)
Link.create("title"=>"Clean Architecture", "url"=>"http://manuel.kiessling.net/2012/09/28/applying-the-clean-architecture-to-go-applications/", "active"=>true)
Link.create("title"=>"Case Switching (vim)", "url"=>"http://vim.wikia.com/wiki/Switching_case_of_characters", "active"=>true)
Link.create("title"=>"Surround (vim)", "url"=>"https://github.com/tpope/vim-surroun", "active"=>true)
Link.create("title"=>"Belfast Half Reg (23rd Feb)", "url"=>"http://www.belfastcitymarathon.com/half-marathon", "active"=>true)
Link.create("title"=>"Jessica Lord (blog)", "url"=>"http://jlord.us/", "active"=>true)
Link.create("title"=>"does what?", "url"=>"http://doeswhat.com/", "active"=>true)
Link.create("title"=>"CodeClimate Ticket", "url"=>"https://shopkeep.atlassian.net/servicedesk/customer/portal/1/DESK-2140", "active"=>true)
Link.create("title"=>"VIM Rails", "url"=>"https://github.com/tpope/vim-rails", "active"=>true)
Link.create("title"=>"Dominic Rodger BLOG", "url"=>"https://www.dominicrodger.com/", "active"=>true)
Link.create("title"=>"Inventory Retro", "url"=>"https://trello.com/b/v5Pyi3QL/inventory-retro", "active"=>true)
Link.create("title"=>"Go Hugo", "url"=>"https://gohugo.io/", "active"=>true)
Link.create("title"=>"Rails status symbols", "url"=>"http://billpatrianakos.me/blog/2013/10/13/list-of-rails-status-code-symbols/", "active"=>true)
Link.create("title"=>"Python meetup API", "url"=>"https://github.com/meetup/python-api-client", "active"=>true)
Link.create("title"=>"Flilipp Blog", "url"=>"https://blog.filippo.io/", "active"=>true)
Link.create("title"=>"Jenkins Fail", "url"=>"https://jenkins-engineering.posrip.com/job/Backoffice-CI/25471/console", "active"=>true)
Link.create("title"=>"Exercism", "url"=>"exercism.io", "active"=>true)
Link.create("title"=>"Noisy Web App", "url"=>"http://www.noisli.com/", "active"=>true)
Link.create("title"=>"Notes on TDD", "url"=>"http://stanislaw.github.io/2016/01/25/notes-on-test-driven-development-by-example-by-kent-beck.html", "active"=>true)
Link.create("title"=>"@dhh trolling again", "url"=>"http://rubyonrails.org/doctrine/?utm_source=rubyweekly&utm_medium=email", "active"=>true)
Link.create("title"=>"Rails Mistakes", "url"=>"http://www.toptal.com/ruby-on-rails/top-10-mistakes-that-rails-programmers-make", "active"=>true)
Link.create("title"=>"The high price of free", "url"=>"http://alistapart.com/article/the-high-price-of-free", "active"=>true)
Link.create("title"=>"Scripting Blog", "url"=>"http://scripting.com/", "active"=>true)
Link.create("title"=>"Design Patterns", "url"=>"https://sourcemaking.com/design_patterns", "active"=>true)
Link.create("title"=>"Vim Golf", "url"=>"http://www.vimgolf.com/", "active"=>true)
Link.create("title"=>"VIM Rails plugins", "url"=>"https://medium.com/efficient-rails/6-vim-plugins-that-will-give-you-ruby-editing-super-powers-32bd94570def#.a1e6di1kx", "active"=>true)
Link.create("title"=>"Software Engineering Daily", "url"=>"http://softwareengineeringdaily.com/2015/11/02/erlang-with-joe-armstrong/", "active"=>true)
Link.create("title"=>"Daves says this is interesting", "url"=>"http://www.smashcompany.com/technology/a-message-hospital-or-dead-letter-queue-where-messages-got-sent-if-they-failed", "active"=>true)
Link.create("title"=>"Moving from cucumber to github", "url"=>"http://zsoltfabok.com/blog/2013/08/from-cucumber-to-turnip/", "active"=>true)
Link.create("title"=>"Turnip", "url"=>"https://github.com/jnicklas/turnip", "active"=>true)
Link.create("title"=>"Logging V Instrumentation", "url"=>"http://peter.bourgon.org/blog/2016/02/07/logging-v-instrumentation.html", "active"=>true)
Link.create("title"=>"Efficient Rails", "url"=>"https://www.efficientrails.com/", "active"=>true)
Link.create("title"=>"Flexible Dockerized Phoenix Deployments.md", "url"=>"https://gist.github.com/jswny/83e03537830b0d997924e8f1965d88bc\n", "active"=>true)
Link.create("title"=>"Slack (Github)", "url"=>"https://slack.github.com/", "active"=>false)
